<?php
require_once __DIR__ . '/db.php';
if (!isConfigured()) { header('Location: setup.php'); exit; }
$error = '';
if (empty($_SESSION['admin_id']) && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $email = trim($_POST['email'] ?? ''); $password = $_POST['password'] ?? '';
    $stmt = database()->prepare('SELECT * FROM admins WHERE email = ?'); $stmt->execute([$email]); $admin = $stmt->fetch(PDO::FETCH_ASSOC);
    if ($admin && password_verify($password, $admin['password_hash'])) { $_SESSION['admin_id'] = $admin['id']; $_SESSION['admin_name'] = $admin['name']; header('Location: admin.php'); exit; }
    $error = 'Invalid email or password.';
}
if (empty($_SESSION['admin_id'])): ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Login | KGN</title><link rel="stylesheet" href="assets/style.css"></head><body class="center-page"><main class="auth-card"><span class="eyebrow">ADMIN AREA</span><h1>Welcome back.</h1><p>Sign in to view student registrations.</p><?php if ($error): ?><div class="alert error"><?=esc($error)?></div><?php endif; ?><form method="post"><label>Email<input type="email" name="email" required autofocus></label><label>Password<input type="password" name="password" required></label><button>Sign in</button></form><a class="text-link" href="index.php">← Return to website</a></main></body></html><?php exit; endif;
$students = database()->query('SELECT registration_number,full_name,phone,email,course,address,created_at FROM students ORDER BY id DESC')->fetchAll(PDO::FETCH_ASSOC);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Student Records | KGN</title><link rel="stylesheet" href="assets/style.css"></head><body class="admin-page"><header class="admin-header"><div><span class="eyebrow">KGN ADMIN</span><h1>Student registrations</h1></div><div><span>Signed in as <?=esc($_SESSION['admin_name'])?></span><a class="button small" href="logout.php">Log out</a></div></header><main class="records"><div class="record-summary"><strong><?=count($students)?></strong><span>Total registrations</span></div><div class="table-wrap"><table><thead><tr><th>Registration no.</th><th>Student</th><th>Contact</th><th>Course</th><th>Address</th><th>Registered</th></tr></thead><tbody><?php if (!$students): ?><tr><td colspan="6" class="empty">No student registrations yet.</td></tr><?php else: foreach($students as $student): ?><tr><td><b><?=esc($student['registration_number'])?></b></td><td><?=esc($student['full_name'])?></td><td><?=esc($student['phone'])?><br><small><?=esc($student['email'])?></small></td><td><?=esc($student['course'])?></td><td><?=esc($student['address'])?></td><td><?=esc(date('d M Y', strtotime($student['created_at'])))?></td></tr><?php endforeach; endif; ?></tbody></table></div></main></body></html>
